namespace: "sample"
namePrefix: "sample"
ui:
  service:
    type: ClusterIP
    port: 8080
    targetPort: 80
  image: "nginx:latest"
  imagePullSecrets: []
  imagePullPolicy: IfNotPresent
  annotations:
    tacokumo.io/managed-by: "portal-controller"
  podAnnotations:
    tacokumo.io/managed-by: "portal-controller"