main:
  applicationName: nginx-app
  replicaCount: 1
  image: "nginx:latest"
  imagePullSecrets: []
  imagePullPolicy: IfNotPresent
  annotations:
    tacokumo.io/managed-by: "portal-controller"
  podAnnotations:
    tacokumo.io/managed-by: "portal-controller"
  envFrom: []