# This rule is not used by the project portal-controller-kubernetes itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over tacokumo.github.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: portal-controller-kubernetes
    app.kubernetes.io/managed-by: kustomize
  name: portal-admin-role
rules:
- apiGroups:
  - tacokumo.github.io
  resources:
  - portals
  verbs:
  - '*'
- apiGroups:
  - tacokumo.github.io
  resources:
  - portals/status
  verbs:
  - get
