## Append samples of your project ##
resources:
- tacokumo.github.io_v1alpha1_application.yaml
- tacokumo.github.io_v1alpha1_portal.yaml
- v1alpha1_release.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
