apiVersion: tacokumo.github.io/v1alpha1
kind: Release
metadata:
  labels:
    app.kubernetes.io/name: portal-controller-kubernetes
    app.kubernetes.io/managed-by: kustomize
  name: release-sample
spec:
  # TODO(user): Add fields here
